### ISSUE TITLE
Not quite perfect

### ISSUE THREAD

**Issue by ronag** [dalecurtis/llama-demo#1]
Please try with the following source file and see how it works. For me there are still distortions.

https://s3.amazonaws.com/ronagyboffins/tmp/tone.flac

Actually, mp3 is not perfect even with the repo checked out as is.

**Comment by ronag** [comment]
Actually, lame always pads the beginning with exactly 576 samples which leads to perfect playback.

**Comment by dalecurtis** [comment]
Whoops, sorry missed this comment so long ago. Did you figure out the issue? Are you converting that flac into an mp3 or mp4 file and then using it with the demo code?
