### ISSUE TITLE
Invalid Access Error

### ISSUE THREAD

**Issue by ronag** [dalecurtis/llama-demo#2]
Sometimes I get the following: 

`Uncaught InvalidAccessError: Failed to set the 'appendWindowStart' property on 'SourceBuffer': The value provided (4.632) is outside the range (0, 4.632].`

I create the files using:

```
ffmpeg -i sintel.flac -f segment -segment_time 5 %d.wav

for f in *.wav ; do lame $f ; done
```

**Comment by dalecurtis** [comment]
Seems like it might be a floating point precision issue. I'll forward to our MSE folk and see if this is still a problem. Do you have the issue setup on a demo page somewhere? Sorry for missing this notification so long ago.

**Comment by chaselambda** [comment]
I believe if you first set `appendWindowEnd` before `appendWindowStart` you won't get this issue. It's a bandaid but seems to work.

**Comment by wolenetz** [comment]
MSE folk on here now :)
The upper bound is actually exclusive, and the lower bound is actually inclusive. There's a bug in the log message itself in Chromium: it should have shown as "...is outside the range [0, 4.632)." The logic behind that follows spec: on setting `appendWindowStart`, if the new value is less than 0 or greater than **or equal to** `appendWindowEnd` then throw a TypeError exception and abort these steps.

To track this, I filed Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1062424

https://github.com/dalecurtis/llama-demo/issues/2#issuecomment-597910726 is correct: Setting `appendWindowEnd` to be higher than the value that you will subsequently set `appendWindowStart` as is the way to correctly operate that API. It may first be required to set `appendWindowStart` temporarily to a lower value to ensure sequence of attribute setting operations satisfies the bounds checks.

I'll mark this closed here, but please re-open if this doesn't fix the issue you're having (or even better, comment on that Chromium bug.)

Edit: I can't mark this closed. @dalecurtis should be able to though.
